apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
type: Opaque
stringData:
  username: root
  password: password
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-minio-credentials
type: Opaque
stringData:
  host: http://minio:9000
  accesskey: admin
  secretkey: password
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mongodump
spec:
  template:
    spec:
      containers:
        - name: mongodump
          image: bitnami/mongodb:latest
          command: ["sh", "-c", "rm -rf /tmp/*; mongodump --host mongodb --username $MONGODB_USERNAME --password $MONGODB_PASSWORD --out=/tmp/backup; tar -czvf /tmp/backup-$(date +%Y-%m-%d-%H-%M-%S).tar.gz -C /tmp/backup .;"]
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: password
          volumeMounts:
            - name: dump
              mountPath: /tmp
        - name: mc
          image: minio/mc
          command: ["sh", "-c", "mc alias set myminio $host $accesskey $secretkey; mc mb --ignore-existing --with-lock myminio/mongo; ls /tmp; mc cp /tmp/*.tar.gz myminio/mongo/ --recursive --no-color --quiet"]
          envFrom:
            - secretRef:
                name: mongo-minio-credentials
          volumeMounts:
            - name: dump
              mountPath: /tmp
      restartPolicy: Never
      volumes:
        - name: dump
          emptyDir: {}
      imagePullSecrets:
        - name: regcred

