apiVersion: v1
kind: Secret
metadata:
  name: postgresql-creds
type: Opaque
stringData:
  PGUSER: postgres
  PGPASSWORD: password
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-minio-creds
type: Opaque
stringData:
  host: http://minio:9000
  accesskey: admin
  secretkey: password
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-config
type: Opaque
stringData:
  PGHOST: postgresql.default.svc
---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-backup
spec:
  template:
    spec:
      containers:
      - name: postgresql-backup
        image: postgres
        command: [ "/bin/bash", "-c"]
        args:
        - BACKUP_FILE="backup-$(date +%Y-%m-%d-%H-%M-%S).tar.gz";
          rm -rf /backup/*;
          pg_dumpall -f /backup/backup.sql;
          tar -czvf /backup/$BACKUP_FILE /backup/backup.sql;
        envFrom:
        - secretRef:
            name: postgresql-creds
        - secretRef:
            name: postgresql-config
        volumeMounts:
        - name: backup-volume
          mountPath: /backup
      - name: mc
        image: minio/mc
        command: ["sh", "-c", "mc alias set myminio $host $accesskey $secretkey; mc mb --ignore-existing --with-lock myminio/postgresql; mc cp /backup/*.tar.gz myminio/postgresql/ --recursive --no-color --quiet"]
        envFrom:
        - secretRef:
            name: postgresql-minio-creds
        volumeMounts:
        - name: backup-volume
          mountPath: /backup
      restartPolicy: Never
      volumes:
      - name: backup-volume
        emptyDir: {}

